name: career_roadmap
description: "Career Roadmap."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4
  http: ^0.13.6  # For API calls
  crypto: ^3.0.3 # For password hashing
  percent_indicator: ^4.2.2
  fl_chart: ^0.66.0
  video_player: ^2.7.0
  webview_flutter: ^4.2.1
  path_provider: ^2.0.11
  flutter_pdfview: ^1.2.3
  supabase_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1   # ← added

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400

# ---- App icon config ----
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
